# -*- coding: utf-8 -*-
"""weather_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ma99BD-NgiydnYrbEwNRhG6Pj5eMXMgY
"""

# Import required libraries
import requests
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

# Set Seaborn style for better visuals
sns.set(style="darkgrid")

# ============ CONFIGURATION ============
API_KEY = 'b99e0b822efcfe6769da705a2258cda0'   # 🔁 Replace this with your OpenWeatherMap API Key
CITY = 'Mumbai'
UNITS = 'metric'  # For Celsius. Use 'imperial' for Fahrenheit.
# =======================================

# Build the API request URL
url = f'https://api.openweathermap.org/data/2.5/forecast?q={CITY}&appid={API_KEY}&units={UNITS}'

# Send the request to OpenWeatherMap API
response = requests.get(url)

# Check if the response was successful
if response.status_code == 200:
    data = response.json()

    # Prepare data for plotting
    dates = []
    temps = []

    for entry in data['list']:
        timestamp = datetime.datetime.fromtimestamp(entry['dt'])
        temperature = entry['main']['temp']
        dates.append(timestamp)
        temps.append(temperature)

    # Plot the data
    plt.figure(figsize=(14, 6))
    sns.lineplot(x=dates, y=temps, marker='o', color='blue')
    plt.title(f"5-Day Temperature Forecast for {CITY}", fontsize=18)
    plt.xlabel("Date and Time", fontsize=12)
    plt.ylabel("Temperature (°C)", fontsize=12)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

else:
    print("Error fetching data from OpenWeatherMap API.")
    print(f"Status Code: {response.status_code}, Message: {response.text}")